#pragma once

// Generated by tests/noveo/generate_request_fields.py from the pinned api.tl schema.
#include "scheme.h"
#include <optional>

namespace Noveo {
template <mtpTypeId Type> struct RequestFields;

template <> struct RequestFields<mtpc_messages_editMessage> {
	MTPint flags;
	MTPInputPeer peer;
	MTPint id;
	MTPstring message;
	MTPInputMedia media;
	MTPReplyMarkup reply_markup;
	MTPVector<MTPMessageEntity> entities;
	MTPint schedule_date;
	MTPint schedule_repeat_period;
	MTPint quick_reply_shortcut_id;
	MTPInputRichMessage rich_message;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& peer.read(from, end)
			&& id.read(from, end)
			&& (!(flags.v & (1U << 11)) || message.read(from, end))
			&& (!(flags.v & (1U << 14)) || media.read(from, end))
			&& (!(flags.v & (1U << 2)) || reply_markup.read(from, end))
			&& (!(flags.v & (1U << 3)) || entities.read(from, end))
			&& (!(flags.v & (1U << 15)) || schedule_date.read(from, end))
			&& (!(flags.v & (1U << 18)) || schedule_repeat_period.read(from, end))
			&& (!(flags.v & (1U << 17)) || quick_reply_shortcut_id.read(from, end))
			&& (!(flags.v & (1U << 23)) || rich_message.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_getMessageEditData> {
	MTPInputPeer peer;
	MTPint id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return peer.read(from, end)
			&& id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_deleteMessages> {
	MTPint flags;
	MTPVector<MTPint> id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_deleteMessages> {
	MTPInputChannel channel;
	MTPVector<MTPint> id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_sendVote> {
	MTPInputPeer peer;
	MTPint msg_id;
	MTPVector<MTPbytes> options;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return peer.read(from, end)
			&& msg_id.read(from, end)
			&& options.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_getPollResults> {
	MTPInputPeer peer;
	MTPint msg_id;
	MTPlong poll_hash;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return peer.read(from, end)
			&& msg_id.read(from, end)
			&& poll_hash.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_getPollVotes> {
	MTPint flags;
	MTPInputPeer peer;
	MTPint id;
	MTPbytes option;
	MTPstring offset;
	MTPint limit;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& peer.read(from, end)
			&& id.read(from, end)
			&& (!(flags.v & (1U << 0)) || option.read(from, end))
			&& (!(flags.v & (1U << 1)) || offset.read(from, end))
			&& limit.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_updatePinnedMessage> {
	MTPint flags;
	MTPInputPeer peer;
	MTPint id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& peer.read(from, end)
			&& id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_unpinAllMessages> {
	MTPint flags;
	MTPInputPeer peer;
	MTPint top_msg_id;
	MTPInputPeer saved_peer_id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& peer.read(from, end)
			&& (!(flags.v & (1U << 0)) || top_msg_id.read(from, end))
			&& (!(flags.v & (1U << 1)) || saved_peer_id.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_search> {
	MTPint flags;
	MTPInputPeer peer;
	MTPstring q;
	MTPInputPeer from_id;
	MTPInputPeer saved_peer_id;
	MTPVector<MTPReaction> saved_reaction;
	MTPint top_msg_id;
	MTPMessagesFilter filter;
	MTPint min_date;
	MTPint max_date;
	MTPint offset_id;
	MTPint add_offset;
	MTPint limit;
	MTPint max_id;
	MTPint min_id;
	MTPlong hash;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& peer.read(from, end)
			&& q.read(from, end)
			&& (!(flags.v & (1U << 0)) || from_id.read(from, end))
			&& (!(flags.v & (1U << 2)) || saved_peer_id.read(from, end))
			&& (!(flags.v & (1U << 3)) || saved_reaction.read(from, end))
			&& (!(flags.v & (1U << 1)) || top_msg_id.read(from, end))
			&& filter.read(from, end)
			&& min_date.read(from, end)
			&& max_date.read(from, end)
			&& offset_id.read(from, end)
			&& add_offset.read(from, end)
			&& limit.read(from, end)
			&& max_id.read(from, end)
			&& min_id.read(from, end)
			&& hash.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_searchGlobal> {
	MTPint flags;
	MTPint folder_id;
	MTPInputChannel community;
	MTPstring q;
	MTPMessagesFilter filter;
	MTPint min_date;
	MTPint max_date;
	MTPint offset_rate;
	MTPInputPeer offset_peer;
	MTPint offset_id;
	MTPint limit;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& (!(flags.v & (1U << 0)) || folder_id.read(from, end))
			&& (!(flags.v & (1U << 4)) || community.read(from, end))
			&& q.read(from, end)
			&& filter.read(from, end)
			&& min_date.read(from, end)
			&& max_date.read(from, end)
			&& offset_rate.read(from, end)
			&& offset_peer.read(from, end)
			&& offset_id.read(from, end)
			&& limit.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_search> {
	MTPint flags;
	MTPstring q;
	MTPint limit;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& q.read(from, end)
			&& limit.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_resolveUsername> {
	MTPint flags;
	MTPstring username;
	MTPstring referer;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& username.read(from, end)
			&& (!(flags.v & (1U << 0)) || referer.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_addContact> {
	MTPint flags;
	MTPInputUser id;
	MTPstring first_name;
	MTPstring last_name;
	MTPstring phone;
	MTPTextWithEntities note;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& id.read(from, end)
			&& first_name.read(from, end)
			&& last_name.read(from, end)
			&& phone.read(from, end)
			&& (!(flags.v & (1U << 1)) || note.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_deleteContacts> {
	MTPVector<MTPInputUser> id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_block> {
	MTPint flags;
	MTPInputPeer id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_unblock> {
	MTPint flags;
	MTPInputPeer id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_contacts_getBlocked> {
	MTPint flags;
	MTPint offset;
	MTPint limit;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& offset.read(from, end)
			&& limit.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_account_updateProfile> {
	MTPint flags;
	MTPstring first_name;
	MTPstring last_name;
	MTPstring about;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& (!(flags.v & (1U << 0)) || first_name.read(from, end))
			&& (!(flags.v & (1U << 1)) || last_name.read(from, end))
			&& (!(flags.v & (1U << 2)) || about.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_account_updateUsername> {
	MTPstring username;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return username.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_account_checkUsername> {
	MTPstring username;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return username.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_photos_uploadProfilePhoto> {
	MTPint flags;
	MTPInputUser bot;
	MTPInputFile file;
	MTPInputFile video;
	MTPdouble video_start_ts;
	MTPVideoSize video_emoji_markup;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& (!(flags.v & (1U << 5)) || bot.read(from, end))
			&& (!(flags.v & (1U << 0)) || file.read(from, end))
			&& (!(flags.v & (1U << 1)) || video.read(from, end))
			&& (!(flags.v & (1U << 2)) || video_start_ts.read(from, end))
			&& (!(flags.v & (1U << 4)) || video_emoji_markup.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_photos_deletePhotos> {
	MTPVector<MTPInputPhoto> id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_account_getAuthorizations> {
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return from == end;
	}
};

template <> struct RequestFields<mtpc_account_resetAuthorization> {
	MTPlong hash;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return hash.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_auth_resetAuthorizations> {
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return from == end;
	}
};

template <> struct RequestFields<mtpc_messages_createChat> {
	MTPint flags;
	MTPVector<MTPInputUser> users;
	MTPstring title;
	MTPint ttl_period;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& users.read(from, end)
			&& title.read(from, end)
			&& (!(flags.v & (1U << 0)) || ttl_period.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_createChannel> {
	MTPint flags;
	MTPstring title;
	MTPstring about;
	MTPInputGeoPoint geo_point;
	MTPstring address;
	MTPint ttl_period;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& title.read(from, end)
			&& about.read(from, end)
			&& (!(flags.v & (1U << 2)) || geo_point.read(from, end))
			&& (!(flags.v & (1U << 2)) || address.read(from, end))
			&& (!(flags.v & (1U << 4)) || ttl_period.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_joinChannel> {
	MTPInputChannel channel;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_leaveChannel> {
	MTPInputChannel channel;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_deleteChatUser> {
	MTPint flags;
	MTPlong chat_id;
	MTPInputUser user_id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& chat_id.read(from, end)
			&& user_id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_addChatUser> {
	MTPlong chat_id;
	MTPInputUser user_id;
	MTPint fwd_limit;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return chat_id.read(from, end)
			&& user_id.read(from, end)
			&& fwd_limit.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_inviteToChannel> {
	MTPInputChannel channel;
	MTPVector<MTPInputUser> users;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& users.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_editChatTitle> {
	MTPlong chat_id;
	MTPstring title;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return chat_id.read(from, end)
			&& title.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_editTitle> {
	MTPInputChannel channel;
	MTPstring title;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& title.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_editChatAbout> {
	MTPInputPeer peer;
	MTPstring about;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return peer.read(from, end)
			&& about.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_editChatAdmin> {
	MTPlong chat_id;
	MTPInputUser user_id;
	MTPBool is_admin;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return chat_id.read(from, end)
			&& user_id.read(from, end)
			&& is_admin.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_editAdmin> {
	MTPint flags;
	MTPInputChannel channel;
	MTPInputUser user_id;
	MTPChatAdminRights admin_rights;
	MTPstring rank;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& channel.read(from, end)
			&& user_id.read(from, end)
			&& admin_rights.read(from, end)
			&& (!(flags.v & (1U << 0)) || rank.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_editBanned> {
	MTPInputChannel channel;
	MTPInputPeer participant;
	MTPChatBannedRights banned_rights;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& participant.read(from, end)
			&& banned_rights.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_updateUsername> {
	MTPInputChannel channel;
	MTPstring username;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& username.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_checkUsername> {
	MTPInputChannel channel;
	MTPstring username;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& username.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_editChatDefaultBannedRights> {
	MTPInputPeer peer;
	MTPChatBannedRights banned_rights;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return peer.read(from, end)
			&& banned_rights.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_getFullChat> {
	MTPlong chat_id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return chat_id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_getFullChannel> {
	MTPInputChannel channel;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_getParticipants> {
	MTPInputChannel channel;
	MTPChannelParticipantsFilter filter;
	MTPint offset;
	MTPint limit;
	MTPlong hash;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& filter.read(from, end)
			&& offset.read(from, end)
			&& limit.read(from, end)
			&& hash.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_getParticipant> {
	MTPInputChannel channel;
	MTPInputPeer participant;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& participant.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_deleteChat> {
	MTPlong chat_id;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return chat_id.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_deleteHistory> {
	MTPint flags;
	MTPInputPeer peer;
	MTPint max_id;
	MTPint min_date;
	MTPint max_date;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return flags.read(from, end)
			&& peer.read(from, end)
			&& max_id.read(from, end)
			&& (!(flags.v & (1U << 2)) || min_date.read(from, end))
			&& (!(flags.v & (1U << 3)) || max_date.read(from, end))
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_deleteChannel> {
	MTPInputChannel channel;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_messages_editChatPhoto> {
	MTPlong chat_id;
	MTPInputChatPhoto photo;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return chat_id.read(from, end)
			&& photo.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_channels_editPhoto> {
	MTPInputChannel channel;
	MTPInputChatPhoto photo;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return channel.read(from, end)
			&& photo.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_account_getPrivacy> {
	MTPInputPrivacyKey key;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return key.read(from, end)
			&& from == end;
	}
};

template <> struct RequestFields<mtpc_account_setPrivacy> {
	MTPInputPrivacyKey key;
	MTPVector<MTPInputPrivacyRule> rules;
	bool read(const mtpBuffer &body) {
		auto from = body.constData() + 1;
		const auto end = body.constData() + body.size();
		return key.read(from, end)
			&& rules.read(from, end)
			&& from == end;
	}
};

template <mtpTypeId Type>
std::optional<RequestFields<Type>> ReadRequest(const mtpBuffer &body) {
	if (body.isEmpty() || uint32(body.front()) != Type) return std::nullopt;
	auto result = RequestFields<Type>();
	return result.read(body) ? std::optional(result) : std::nullopt;
}
} // namespace Noveo
