"""Regenerate typed native request readers after updating api.tl."""
from pathlib import Path
import re
names='messages.editMessage messages.getMessageEditData messages.deleteMessages channels.deleteMessages messages.sendVote messages.getPollResults messages.getPollVotes messages.updatePinnedMessage messages.unpinAllMessages messages.search messages.searchGlobal contacts.search contacts.resolveUsername contacts.addContact contacts.deleteContacts contacts.block contacts.unblock contacts.getBlocked account.updateProfile account.updateUsername account.checkUsername photos.uploadProfilePhoto photos.deletePhotos account.getAuthorizations account.resetAuthorization auth.resetAuthorizations messages.createChat channels.createChannel channels.joinChannel channels.leaveChannel messages.deleteChatUser messages.addChatUser channels.inviteToChannel messages.editChatTitle channels.editTitle messages.editChatAbout messages.editChatAdmin channels.editAdmin channels.editBanned channels.updateUsername channels.checkUsername messages.editChatDefaultBannedRights messages.getFullChat channels.getFullChannel channels.getParticipants channels.getParticipant messages.deleteChat messages.deleteHistory channels.deleteChannel messages.editChatPhoto channels.editPhoto account.getPrivacy account.setPrivacy'.split()
root = Path(__file__).resolve().parents[2]
schema=(root / 'Telegram/SourceFiles/mtproto/scheme/api.tl').read_text()
def typ(t):
 if t=='#':return 'MTPint'
 if t.startswith('Vector<'):return 'MTPVector<'+typ(t[7:-1])+'>'
 return 'MTP'+t.replace('.','_')
text='#pragma once\n\n// Generated by tests/noveo/generate_request_fields.py from the pinned api.tl schema.\n#include "scheme.h"\n#include <optional>\n\nnamespace Noveo {\ntemplate <mtpTypeId Type> struct RequestFields;\n'
for name in names:
 m=re.search(r'^'+re.escape(name)+r'#[0-9a-f]+(.*?) = ',schema,re.M);assert m,name
 fields=[]
 for word in m[1].split():
  key,t=word.split(':',1); opt=re.match(r'(flags\d*)\.(\d+)\?(.*)',t)
  if opt:
   flag,bit,t=opt.groups()
   if t=='true':continue
  fields.append((key,typ(t),opt.groups()[:2] if opt else None))
 cpp=name.replace('.','_');text+=f'\ntemplate <> struct RequestFields<mtpc_{cpp}> {{\n'
 for key,t,opt in fields:text+=f'\t{t} {key};\n'
 text+='\tbool read(const mtpBuffer &body) {\n\t\tauto from = body.constData() + 1;\n\t\tconst auto end = body.constData() + body.size();\n\t\treturn '
 checks=[]
 for key,t,opt in fields:
  check=f'{key}.read(from, end)'
  if opt:check=f'(!({opt[0]}.v & (1U << {opt[1]})) || {check})'
  checks.append(check)
 text+= ('\n\t\t\t&& '.join(checks)+'\n\t\t\t&& ' if checks else '')+'from == end;\n\t}\n};\n'
text+='''
template <mtpTypeId Type>
std::optional<RequestFields<Type>> ReadRequest(const mtpBuffer &body) {
	if (body.isEmpty() || uint32(body.front()) != Type) return std::nullopt;
	auto result = RequestFields<Type>();
	return result.read(body) ? std::optional(result) : std::nullopt;
}
} // namespace Noveo
'''
(root / 'Telegram/SourceFiles/noveo/request_fields.h').write_text(text)
